### ISSUE TITLE
when i set the weekTextColor has a problem

### ISSUE THREAD

**Issue by helinfeng** [loonggg/WeekCalendar#1]
com.android.layoutlib.bridge.android.BridgeContext cannot be cast to android.support.v7.app.AppCompatActivity  
at noman.weekcalendar.view.WeekPager.initPager(WeekPager.java:54)   at noman.weekcalendar.view.WeekPager.initialize(WeekPager.java:47)   at noman.weekcalendar.view.WeekPager.<init>(WeekPager.java:38)   at noman.weekcalendar.WeekCalendar.init(WeekCalendar.java:69)   at noman.weekcalendar.WeekCalendar.<init>(WeekCalendar.java:49)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at

android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard

i want to change the weekTextColor ,but now this way can't!
in my studio said this error, maybe my api is very high,i hope you can solve this problem thanks;

**Comment by loonggg** [comment]
ok，copy that.

**Comment by loonggg** [comment]
I have already modified . You replace the depend on [ compile 'com.github.loonggg:WeekCalendar:v1.3'].
